name: SonarCloud Scan

on:
  push:
    branches: 
      -"main"
      -"QA"
  pull_request:
    branches:
      -"main"
      -"QA"
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for complete history

      # Install dependencies server
      - name: Install server dependencies
        run: npm ci --prefix server

      # Install dependencies client
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Run Tests with Coverage
        run: npm run test:coverage

      # Analisi SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
